### ISSUE TITLE
Link GitHub profile

### ISSUE THREAD

**Issue by gayaviswa** [Jayshil/stark#26]
Please link the GitHub profile for Gayathri Viswanath under the description of contribution to the UVES version of STARK in the README.
The link to Gayathri's GitHub profile is https://github.com/gayaviswa

**Comment by Jayshil** [comment]
Hey @gayaviswa,

Thank you for pointing this out -- I have now added your GitHub to the [ReadMe](https://github.com/Jayshil/stark) of the repo and also to the [documentation webpage](https://stark-package.readthedocs.io/en/latest/). Will be closing the issue now!

Cheers,
J.
